/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_juanflores;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JD
 */
public class Examen1P2_JuanFlores extends javax.swing.JFrame {
    
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    ArrayList<Equipo>  equipos = new ArrayList();
    
    /**
     * Creates new form Examen1P2_JuanFlores
     */
    public Examen1P2_JuanFlores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        FIFA = new javax.swing.JTabbedPane();
        EquipoEdit = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        EquipoX = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Equipo_Eliminar = new javax.swing.JComboBox<>();
        Elim_equipo = new javax.swing.JButton();
        Estadio = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreEstadio = new javax.swing.JTextField();
        CiudadEstadio = new javax.swing.JTextField();
        CapacidadEstadio = new javax.swing.JTextField();
        Equipo_Estadios = new javax.swing.JComboBox<>();
        AgregarEstadio = new javax.swing.JButton();
        EstadioEdit = new javax.swing.JTabbedPane();
        EstadioX = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Estadio_Eliminar = new javax.swing.JComboBox<>();
        EliminarEstadio = new javax.swing.JButton();
        Jugador = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AgregarJugador = new javax.swing.JButton();
        NombreJugador = new javax.swing.JTextField();
        EdadJugador = new javax.swing.JTextField();
        NacionalidadJ = new javax.swing.JTextField();
        PieJugador = new javax.swing.JTextField();
        EquiposJ = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        TipoJugador = new javax.swing.JComboBox<>();
        JugadorEdit = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        JugadorX = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Eliminar_jugador = new javax.swing.JComboBox<>();
        JugadoElim = new javax.swing.JButton();
        Listar = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        ListarTod = new javax.swing.JButton();
        Simulacion = new javax.swing.JTabbedPane();
        Equipo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreEquipo = new javax.swing.JTextField();
        PaisEquipo = new javax.swing.JTextField();
        AgregarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicio.setBackground(new java.awt.Color(255, 255, 255));

        Titulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Titulo.setText("FIFA VOLTA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        EquipoEdit.addTab("tab1", jPanel2);

        FIFA.addTab("Editar Equipo", EquipoEdit);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("INGRESE EL EQUIPO A ELIMINAR: ");

        Equipo_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Equipo_EliminarMouseClicked(evt);
            }
        });

        Elim_equipo.setText("ELIMINAR");
        Elim_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Elim_equipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel14))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(Equipo_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(Elim_equipo)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addGap(43, 43, 43)
                .addComponent(Equipo_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Elim_equipo)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        EquipoX.addTab("tab1", jPanel7);

        FIFA.addTab("Eliminar Equipo", EquipoX);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("CIUDAD");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("CAPACIDAD");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("EQUIPO");

        Equipo_Estadios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Equipo_EstadiosMouseClicked(evt);
            }
        });
        Equipo_Estadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipo_EstadiosActionPerformed(evt);
            }
        });

        AgregarEstadio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarEstadio.setText("AGREGAR");
        AgregarEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarEstadioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Equipo_Estadios, 0, 251, Short.MAX_VALUE)
                        .addGap(206, 206, 206))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CiudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapacidadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(AgregarEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CiudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CapacidadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Equipo_Estadios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(AgregarEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Estadio.addTab("tab1", jPanel3);

        FIFA.addTab("Agregar Estadio", Estadio);
        FIFA.addTab("Editar Estadio", EstadioEdit);

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setText("INGRESE EL ESTADIO A ELIMINAR: ");

        Estadio_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Estadio_EliminarMouseClicked(evt);
            }
        });

        EliminarEstadio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        EliminarEstadio.setText("ELIMINAR");
        EliminarEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarEstadioMouseClicked(evt);
            }
        });
        EliminarEstadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEstadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel13))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(Estadio_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(EliminarEstadio)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addComponent(Estadio_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(EliminarEstadio)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        EstadioX.addTab("tab1", jPanel5);

        FIFA.addTab("Eliminar Estadio", EstadioX);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("EDAD");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("NOMBRE");

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("NACIONALIDAD");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("EQUIPO");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("PIE  HABIL");

        AgregarJugador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AgregarJugador.setText("AGREGAR");
        AgregarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarJugadorMouseClicked(evt);
            }
        });
        AgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarJugadorActionPerformed(evt);
            }
        });

        PieJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PieJugadorActionPerformed(evt);
            }
        });

        EquiposJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EquiposJMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("TIPO DE JUGADOR");

        TipoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(63, 63, 63)
                                .addComponent(EdadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(163, 163, 163))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EquiposJ, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PieJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(NacionalidadJ, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(197, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel12)
                .addGap(36, 36, 36)
                .addComponent(TipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NacionalidadJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PieJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(AgregarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EquiposJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Jugador.addTab("tab1", jPanel4);

        FIFA.addTab("Ingresar Jugador", Jugador);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        JugadorEdit.addTab("tab1", jPanel6);

        FIFA.addTab("Editar Jugador", JugadorEdit);

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setText("INGRESE EL  JUGADOR AL ELIMINAR:");

        Eliminar_jugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Eliminar_jugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_jugadorMouseClicked(evt);
            }
        });

        JugadoElim.setText("ELIMINAR");
        JugadoElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadoElimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JugadoElim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Eliminar_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(JugadoElim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        JugadorX.addTab("tab1", jPanel8);

        FIFA.addTab("Eliminar Jugador", JugadorX);

        d.setColumns(20);
        d.setRows(5);
        jScrollPane1.setViewportView(d);

        ListarTod.setText("LISTAR");
        ListarTod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarTodMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(ListarTod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(ListarTod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        Listar.addTab("tab1", jPanel9);

        FIFA.addTab("Listar Todo", Listar);
        FIFA.addTab("Simulacion", Simulacion);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAIS");

        AgregarEquipo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        AgregarEquipo.setText("AGREGAR");
        AgregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarEquipoMouseClicked(evt);
            }
        });
        AgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaisEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(AgregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(AgregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        Equipo.addTab("tab1", jPanel1);

        FIFA.addTab("Ingresar equipo", Equipo);

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(Titulo))
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(FIFA, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(FIFA, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        FIFA.getAccessibleContext().setAccessibleName("INGRESAR EQUIPO\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEquipoActionPerformed
       
        String nombre=NombreEquipo.getText();
        String pais = PaisEquipo.getText();
        
        equipos.add(new Equipo(nombre, pais));
        
        JOptionPane.showMessageDialog(this, "Equipo Ingresado Exitosamente");
        
    }//GEN-LAST:event_AgregarEquipoActionPerformed

    private void PieJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PieJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PieJugadorActionPerformed

    private void AgregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarEquipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarEquipoMouseClicked

    private void AgregarEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarEstadioMouseClicked
        //NOMBRE, CIUDAD, CAPACIDAD, EQUIPO
        String nombre=NombreEstadio.getText();
        String ciudad=CiudadEstadio.getText();
        int capac = Integer.parseInt(CapacidadEstadio.getText());
        
        estadios.add(new Estadio(nombre, ciudad, capac));
        
        
        JOptionPane.showMessageDialog(this, "Estadio ingresado exitosamente");
    }//GEN-LAST:event_AgregarEstadioMouseClicked

    private void AgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarJugadorActionPerformed

    
    private void AgregarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarJugadorMouseClicked
       
        if(equipos.isEmpty()){
            JOptionPane.showMessageDialog(this, "No puede agregar jugadores si no hay equipos");
            
        }else{
       
         
            
       String tipo = TipoJugador.getSelectedItem().toString();
       
       if("Portero".equals(tipo)){
          String nombre = NombreJugador.getText();
          int edad = Integer.parseInt(EdadJugador.getText());
          String nacionalidad = NacionalidadJ.getText(); 
          String pieJugador = PieJugador.getText();
          
          String equipo = EquiposJ.getSelectedItem().toString();
          jugadores.add(new Portero(nombre, edad, nacionalidad, pieJugador, equipo));
           
       } else if("Defensa".equals(tipo)){
           String nombre = NombreJugador.getText();
           int edad = Integer.parseInt(EdadJugador.getText());
           String nacionalidad = NacionalidadJ.getText();
           String pieJugador = PieJugador.getText();
            
           String equipo = EquiposJ.getSelectedItem().toString();
           jugadores.add(new Defensa(nombre, edad, nacionalidad, pieJugador, equipo));
           
       }else if("Mediocampista".equals(tipo)){
           String nombre = NombreJugador.getText();
           int edad = Integer.parseInt(EdadJugador.getText());
           String nacionalidad = NacionalidadJ.getText();
           String pieJugador = PieJugador.getText();
          
           String equipo = EquiposJ.getSelectedItem().toString();
           jugadores.add(new Mediocampista(nombre, edad, nacionalidad, pieJugador, equipo));
           
       }else if("Delantero".equals(tipo)){
           String nombre = NombreJugador.getText();
           int edad = Integer.parseInt(EdadJugador.getText());
           String nacionalidad = NacionalidadJ.getText();
           String pieJugador = PieJugador.getText();
          
           String equipo = EquiposJ.getSelectedItem().toString();
           jugadores.add(new Delantero(nombre, edad, nacionalidad, pieJugador, equipo));
       }
       
       
       
       
       JOptionPane.showMessageDialog(this, "Jugador Ingresado Exitosamente");
       
        }
    }//GEN-LAST:event_AgregarJugadorMouseClicked

    private void EquiposJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquiposJMouseClicked
        DefaultComboBoxModel modelo = ((DefaultComboBoxModel)EquiposJ.getModel());
        
        for (Equipo equipo : equipos) {
            modelo.addElement(equipo.getNombre());
        } 
    }//GEN-LAST:event_EquiposJMouseClicked

    private void Equipo_EstadiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Equipo_EstadiosMouseClicked
        DefaultComboBoxModel modeloE = ((DefaultComboBoxModel)Equipo_Estadios.getModel());
        
        for (Equipo equipo : equipos) {
            modeloE.addElement(equipo.getNombre());
        }
    }//GEN-LAST:event_Equipo_EstadiosMouseClicked

    private void EliminarEstadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEstadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarEstadioActionPerformed

    private void Estadio_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Estadio_EliminarMouseClicked
        DefaultComboBoxModel modeloEs = ((DefaultComboBoxModel)Estadio_Eliminar.getModel());
        
        for (Estadio estadio : estadios) {
            modeloEs.addElement(estadio.getNombreEs());
        }
    }//GEN-LAST:event_Estadio_EliminarMouseClicked

    private void EliminarEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarEstadioMouseClicked
       
       int pos = Estadio_Eliminar.getSelectedIndex();
       
       DefaultComboBoxModel modeloEst = ((DefaultComboBoxModel)Estadio_Eliminar.getModel());
        
        for (Estadio estadio : estadios) {
            modeloEst.addElement(estadio.getNombreEs());
        }
        
       modeloEst.removeElementAt(pos);
       estadios.remove(pos);
    }//GEN-LAST:event_EliminarEstadioMouseClicked

    private void Equipo_EstadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipo_EstadiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Equipo_EstadiosActionPerformed

    private void Equipo_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Equipo_EliminarMouseClicked
        DefaultComboBoxModel modelo = ((DefaultComboBoxModel)EquiposJ.getModel());
        
        for (Equipo equipo : equipos) {
            modelo.addElement(equipo.getNombre());
        }
    }//GEN-LAST:event_Equipo_EliminarMouseClicked

    private void Elim_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Elim_equipoMouseClicked
        int pos = Equipo_Eliminar.getSelectedIndex();
       
       DefaultComboBoxModel modeloEst = ((DefaultComboBoxModel)Equipo_Eliminar.getModel());
        
        for (Equipo equipo : equipos) {
            modeloEst.addElement(equipo.getNombre());
        }
        
       modeloEst.removeElementAt(pos);
       estadios.remove(pos);
    }//GEN-LAST:event_Elim_equipoMouseClicked

    private void JugadoElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadoElimActionPerformed
         int pos = Eliminar_jugador.getSelectedIndex();
       
       DefaultComboBoxModel modeloEst = ((DefaultComboBoxModel)Eliminar_jugador.getModel());
        
        for (Jugador jugador : jugadores) {
            modeloEst.addElement(jugador.getNombre());
        }
        
       modeloEst.removeElementAt(pos);
       estadios.remove(pos);
    }//GEN-LAST:event_JugadoElimActionPerformed

    private void Eliminar_jugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_jugadorMouseClicked
        DefaultComboBoxModel modelo = ((DefaultComboBoxModel)Eliminar_jugador.getModel());
        
        for (Jugador jugador : jugadores) {
            modelo.addElement(jugador.getNombre());
        }
    }//GEN-LAST:event_Eliminar_jugadorMouseClicked

    private void ListarTodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarTodMouseClicked
        String salida="";
       
        for (int i = 0; i < estadios.size(); i++) {
           salida+=estadios.get(i)+"\n";
        }
        
        for (int i = 0; i < equipos.size(); i++) {
           salida+=equipos.get(i)+"\n";
        }
        
        for (int i = 0; i < jugadores.size(); i++) {
            salida+=jugadores.get(i)+"\n";
        }
        d.setText(salida);
        
        
    }//GEN-LAST:event_ListarTodMouseClicked

    
    public void llenarComboEquipo(){
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_JuanFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_JuanFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_JuanFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1P2_JuanFlores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1P2_JuanFlores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEquipo;
    private javax.swing.JButton AgregarEstadio;
    private javax.swing.JButton AgregarJugador;
    private javax.swing.JTextField CapacidadEstadio;
    private javax.swing.JTextField CiudadEstadio;
    private javax.swing.JTextField EdadJugador;
    private javax.swing.JButton Elim_equipo;
    private javax.swing.JButton EliminarEstadio;
    private javax.swing.JComboBox<String> Eliminar_jugador;
    private javax.swing.JTabbedPane Equipo;
    private javax.swing.JTabbedPane EquipoEdit;
    private javax.swing.JTabbedPane EquipoX;
    private javax.swing.JComboBox<String> Equipo_Eliminar;
    private javax.swing.JComboBox<String> Equipo_Estadios;
    private javax.swing.JComboBox<String> EquiposJ;
    private javax.swing.JTabbedPane Estadio;
    private javax.swing.JTabbedPane EstadioEdit;
    private javax.swing.JTabbedPane EstadioX;
    private javax.swing.JComboBox<String> Estadio_Eliminar;
    private javax.swing.JTabbedPane FIFA;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton JugadoElim;
    private javax.swing.JTabbedPane Jugador;
    private javax.swing.JTabbedPane JugadorEdit;
    private javax.swing.JTabbedPane JugadorX;
    private javax.swing.JTabbedPane Listar;
    private javax.swing.JButton ListarTod;
    private javax.swing.JTextField NacionalidadJ;
    private javax.swing.JTextField NombreEquipo;
    private javax.swing.JTextField NombreEstadio;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JTextField PaisEquipo;
    private javax.swing.JTextField PieJugador;
    private javax.swing.JTabbedPane Simulacion;
    private javax.swing.JComboBox<String> TipoJugador;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextArea d;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
